directories:
  python_path_remote: /Local/ph_keselman/anaconda3/bin/python
  std_error_dir: /storage/ph_keselman/ngutman/stderr/
  std_output_dir: /storage/ph_keselman/ngutman/stdout/
  log_dir: /storage/ph_keselman/ngutman/condor_logs/
  storage_dir_ATLAS: /storage/ph_keselman/ngutman/condor_tests/
  working_dir: /srv01/technion/ngutman/repos/Superradiance/
  condor_executables_dir: /srv01/technion/ngutman/repos/Superradiance/scripts/condor/CondorJobSender
  julia_path_remote: /Local/ph_keselman/julia-1.6.1/bin/julia
username: ngutman
parameters:
  universe: vanilla

